pipeline:
  build:
    image: java:8-alpine
    commands:
      - echo ${TEST}
      - javac Solution.java
      - java Solution

  notify:
    image: eisenxu/drone-ketsu-notification
    host: https://intense-harbor-13956.herokuapp.com
    when:
      status: [ success, failure ]
