pipeline:
  build:
    image: java:8-alpine
    commands:
      - echo $EXAM_EMAIL
      - export TEST=${EXAM_EMAIL}
      - javac Solution.java
      - java Solution

  notify:
    image: eisenxu/drone-ketsu-notification
    host: https://ketsu-backend.herokuapp.com
    when:
      status: [ success, failure ]
